import type { Skin, AppState, InventoryItem } from "./types"

export const DEFAULT_SKINS: Skin[] = [
  { id: "skin-1", name: "Sand Dune", weapon: "P250", wear: "Factory New", price: 143.02, image: "https://s3.upgrader.pro/cdn/items/832/medium.png", rarity: "uncommon" },
  { id: "skin-2", name: "Recoil XM1014", weapon: "Sealed Graffiti", wear: "Monarch Blue", price: 765.94, image: "https://s3.upgrader.pro/cdn/items/23405/medium.png", rarity: "uncommon" },
  { id: "skin-3", name: "Magmatude", weapon: "Charm", wear: "FN", price: 168.61, image: "https://s3.upgrader.pro/cdn/items/15207/medium.png", rarity: "rare" },
  { id: "skin-4", name: "Gold Toof", weapon: "Glock-18", wear: "Well-Worn", price: 2722.97, image: "https://s3.upgrader.pro/cdn/items/14117/medium.png", rarity: "legendary" },
  { id: "skin-5", name: "Moonrise", weapon: "Glock-18", wear: "Battle-Scarred", price: 146.7, image: "https://s3.upgrader.pro/cdn/items/8948/medium.png", rarity: "rare" },
  { id: "skin-6", name: "Kiss♥Love", weapon: "Sawed-Off", wear: "Well-Worn", price: 278.8, image: "https://s3.upgrader.pro/cdn/items/2219/medium.png", rarity: "mythical" },
  { id: "skin-7", name: "Tropical Storm", weapon: "Souvenir SSG 08", wear: "Battle-Scarred", price: 1215.63, image: "https://s3.upgrader.pro/cdn/items/16329/medium.png", rarity: "common" },
  { id: "skin-8", name: "Faulty Wiring", weapon: "FAMAS", wear: "Minimal Wear", price: 141.25, image: "https://s3.upgrader.pro/cdn/items/12328/medium.png", rarity: "uncommon" },
  { id: "skin-9", name: "Liquidation", weapon: "M4A1-S", wear: "Factory New", price: 928.12, image: "https://s3.upgrader.pro/cdn/items/3005/medium.png", rarity: "rare" },
  { id: "skin-10", name: "Half Sleeve", weapon: "FAMAS", wear: "Factory New", price: 145.69, image: "https://s3.upgrader.pro/cdn/items/1039/medium.png", rarity: "common" },
  { id: "skin-11", name: "USTILO (Foil)", weapon: "Sticker", wear: "Boston 2018", price: 999.85, image: "https://s3.upgrader.pro/cdn/items/20945/medium.png", rarity: "rare" },
  { id: "skin-12", name: "Ace Devil", weapon: "Sticker", wear: "Foil", price: 280.13, image: "https://s3.upgrader.pro/cdn/items/12135/medium.png", rarity: "mythical" },
  { id: "skin-13", name: "Autumn Twilly", weapon: "MP5-SD", wear: "Minimal Wear", price: 1088.6, image: "https://s3.upgrader.pro/cdn/items/12351/medium.png", rarity: "rare" },
  { id: "skin-14", name: "Skadoodle", weapon: "Sticker", wear: "Boston 2018", price: 322.44, image: "https://s3.upgrader.pro/cdn/items/17644/medium.png", rarity: "uncommon" },
  { id: "skin-15", name: "Chopper", weapon: "P90", wear: "Well-Worn", price: 158.5, image: "https://s3.upgrader.pro/cdn/items/7448/medium.png", rarity: "rare" },
  { id: "skin-16", name: "Wild Child", weapon: "UMP-45", wear: "Battle-Scarred", price: 238.87, image: "https://s3.upgrader.pro/cdn/items/13631/medium.png", rarity: "mythical" },
  { id: "skin-17", name: "Falcons (Foil) | Austin 2025", weapon: "Sticker Slab", wear: "FN", price: 119.53, image: "https://s3.upgrader.pro/cdn/items/26372/medium.png", rarity: "rare" },
  { id: "skin-18", name: "Weasel", weapon: "Glock-18", wear: "Minimal Wear", price: 138.59, image: "https://s3.upgrader.pro/cdn/items/1728/medium.png", rarity: "rare" },
  { id: "skin-19", name: "Slate", weapon: "AK-47", wear: "Field-Tested", price: 375.23, image: "https://s3.upgrader.pro/cdn/items/2279/medium.png", rarity: "rare" },
  { id: "skin-20", name: "Red Stone", weapon: "SSG 08", wear: "Minimal Wear", price: 963.61, image: "https://s3.upgrader.pro/cdn/items/10886/medium.png", rarity: "uncommon" },
  { id: "skin-21", name: "Sand Dune", weapon: "P250", wear: "Factory New", price: 157.32, image: "https://s3.upgrader.pro/cdn/items/832/medium.png", rarity: "uncommon" },
  { id: "skin-22", name: "Recoil XM1014", weapon: "Sealed Graffiti", wear: "Monarch Blue", price: 842.53, image: "https://s3.upgrader.pro/cdn/items/23405/medium.png", rarity: "uncommon" },
  { id: "skin-23", name: "Magmatude", weapon: "Charm", wear: "FN", price: 185.47, image: "https://s3.upgrader.pro/cdn/items/15207/medium.png", rarity: "rare" },
  { id: "skin-24", name: "Gold Toof", weapon: "Glock-18", wear: "Well-Worn", price: 2995.27, image: "https://s3.upgrader.pro/cdn/items/14117/medium.png", rarity: "legendary" },
  { id: "skin-25", name: "Moonrise", weapon: "Glock-18", wear: "Battle-Scarred", price: 161.37, image: "https://s3.upgrader.pro/cdn/items/8948/medium.png", rarity: "rare" },
  { id: "skin-26", name: "Kiss♥Love", weapon: "Sawed-Off", wear: "Well-Worn", price: 306.68, image: "https://s3.upgrader.pro/cdn/items/2219/medium.png", rarity: "mythical" },
  { id: "skin-27", name: "Tropical Storm", weapon: "Souvenir SSG 08", wear: "Battle-Scarred", price: 1337.19, image: "https://s3.upgrader.pro/cdn/items/16329/medium.png", rarity: "common" },
  { id: "skin-28", name: "Faulty Wiring", weapon: "FAMAS", wear: "Minimal Wear", price: 155.38, image: "https://s3.upgrader.pro/cdn/items/12328/medium.png", rarity: "uncommon" },
  { id: "skin-29", name: "Liquidation", weapon: "M4A1-S", wear: "Factory New", price: 1020.93, image: "https://s3.upgrader.pro/cdn/items/3005/medium.png", rarity: "rare" },
  { id: "skin-30", name: "Half Sleeve", weapon: "FAMAS", wear: "Factory New", price: 160.26, image: "https://s3.upgrader.pro/cdn/items/1039/medium.png", rarity: "common" },
  { id: "skin-31", name: "USTILO (Foil)", weapon: "Sticker", wear: "Boston 2018", price: 1099.84, image: "https://s3.upgrader.pro/cdn/items/20945/medium.png", rarity: "rare" },
  { id: "skin-32", name: "Ace Devil", weapon: "Sticker", wear: "Foil", price: 308.14, image: "https://s3.upgrader.pro/cdn/items/12135/medium.png", rarity: "mythical" },
  { id: "skin-33", name: "Autumn Twilly", weapon: "MP5-SD", wear: "Minimal Wear", price: 1197.46, image: "https://s3.upgrader.pro/cdn/items/12351/medium.png", rarity: "rare" },
  { id: "skin-34", name: "Skadoodle", weapon: "Sticker", wear: "Boston 2018", price: 354.68, image: "https://s3.upgrader.pro/cdn/items/17644/medium.png", rarity: "uncommon" },
  { id: "skin-35", name: "Chopper", weapon: "P90", wear: "Well-Worn", price: 174.35, image: "https://s3.upgrader.pro/cdn/items/7448/medium.png", rarity: "rare" },
  { id: "skin-36", name: "Wild Child", weapon: "UMP-45", wear: "Battle-Scarred", price: 262.76, image: "https://s3.upgrader.pro/cdn/items/13631/medium.png", rarity: "mythical" },
  { id: "skin-37", name: "Falcons (Foil) | Austin 2025", weapon: "Sticker Slab", wear: "FN", price: 131.48, image: "https://s3.upgrader.pro/cdn/items/26372/medium.png", rarity: "rare" },
  { id: "skin-38", name: "Weasel", weapon: "Glock-18", wear: "Minimal Wear", price: 152.45, image: "https://s3.upgrader.pro/cdn/items/1728/medium.png", rarity: "rare" },
  { id: "skin-39", name: "Slate", weapon: "AK-47", wear: "Field-Tested", price: 412.75, image: "https://s3.upgrader.pro/cdn/items/2279/medium.png", rarity: "rare" },
  { id: "skin-40", name: "Red Stone", weapon: "SSG 08", wear: "Minimal Wear", price: 1059.97, image: "https://s3.upgrader.pro/cdn/items/10886/medium.png", rarity: "uncommon" },
  { id: "skin-41", name: "Sand Dune", weapon: "P250", wear: "Factory New", price: 171.62, image: "https://s3.upgrader.pro/cdn/items/832/medium.png", rarity: "uncommon" },
  { id: "skin-42", name: "Recoil XM1014", weapon: "Sealed Graffiti", wear: "Monarch Blue", price: 919.13, image: "https://s3.upgrader.pro/cdn/items/23405/medium.png", rarity: "uncommon" },
  { id: "skin-43", name: "Magmatude", weapon: "Charm", wear: "FN", price: 202.33, image: "https://s3.upgrader.pro/cdn/items/15207/medium.png", rarity: "rare" },
  { id: "skin-44", name: "Gold Toof", weapon: "Glock-18", wear: "Well-Worn", price: 3267.56, image: "https://s3.upgrader.pro/cdn/items/14117/medium.png", rarity: "legendary" },
  { id: "skin-45", name: "Moonrise", weapon: "Glock-18", wear: "Battle-Scarred", price: 176.04, image: "https://s3.upgrader.pro/cdn/items/8948/medium.png", rarity: "rare" },
  { id: "skin-46", name: "Kiss♥Love", weapon: "Sawed-Off", wear: "Well-Worn", price: 334.56, image: "https://s3.upgrader.pro/cdn/items/2219/medium.png", rarity: "mythical" },
  { id: "skin-47", name: "Tropical Storm", weapon: "Souvenir SSG 08", wear: "Battle-Scarred", price: 1458.76, image: "https://s3.upgrader.pro/cdn/items/16329/medium.png", rarity: "common" },
  { id: "skin-48", name: "Faulty Wiring", weapon: "FAMAS", wear: "Minimal Wear", price: 169.50, image: "https://s3.upgrader.pro/cdn/items/12328/medium.png", rarity: "uncommon" },
  { id: "skin-49", name: "Liquidation", weapon: "M4A1-S", wear: "Factory New", price: 1113.74, image: "https://s3.upgrader.pro/cdn/items/3005/medium.png", rarity: "rare" },
  { id: "skin-50", name: "Half Sleeve", weapon: "FAMAS", wear: "Factory New", price: 174.83, image: "https://s3.upgrader.pro/cdn/items/1039/medium.png", rarity: "common" },
  { id: "skin-51", name: "USTILO (Foil)", weapon: "Sticker", wear: "Boston 2018", price: 1199.82, image: "https://s3.upgrader.pro/cdn/items/20945/medium.png", rarity: "rare" },
  { id: "skin-52", name: "Ace Devil", weapon: "Sticker", wear: "Foil", price: 336.16, image: "https://s3.upgrader.pro/cdn/items/12135/medium.png", rarity: "mythical" },
  { id: "skin-53", name: "Autumn Twilly", weapon: "MP5-SD", wear: "Minimal Wear", price: 1306.32, image: "https://s3.upgrader.pro/cdn/items/12351/medium.png", rarity: "rare" },
  { id: "skin-54", name: "Skadoodle", weapon: "Sticker", wear: "Boston 2018", price: 386.93, image: "https://s3.upgrader.pro/cdn/items/17644/medium.png", rarity: "uncommon" },
  { id: "skin-55", name: "Chopper", weapon: "P90", wear: "Well-Worn", price: 190.20, image: "https://s3.upgrader.pro/cdn/items/7448/medium.png", rarity: "rare" },
  { id: "skin-56", name: "Wild Child", weapon: "UMP-45", wear: "Battle-Scarred", price: 286.64, image: "https://s3.upgrader.pro/cdn/items/13631/medium.png", rarity: "mythical" },
  { id: "skin-57", name: "Falcons (Foil) | Austin 2025", weapon: "Sticker Slab", wear: "FN", price: 143.44, image: "https://s3.upgrader.pro/cdn/items/26372/medium.png", rarity: "rare" },
  { id: "skin-58", name: "Weasel", weapon: "Glock-18", wear: "Minimal Wear", price: 166.31, image: "https://s3.upgrader.pro/cdn/items/1728/medium.png", rarity: "rare" },
  { id: "skin-59", name: "Slate", weapon: "AK-47", wear: "Field-Tested", price: 450.28, image: "https://s3.upgrader.pro/cdn/items/2279/medium.png", rarity: "rare" },
  { id: "skin-60", name: "Red Stone", weapon: "SSG 08", wear: "Minimal Wear", price: 1156.33, image: "https://s3.upgrader.pro/cdn/items/10886/medium.png", rarity: "uncommon" },
  { id: "skin-61", name: "Sand Dune", weapon: "P250", wear: "Factory New", price: 185.93, image: "https://s3.upgrader.pro/cdn/items/832/medium.png", rarity: "uncommon" },
  { id: "skin-62", name: "Recoil XM1014", weapon: "Sealed Graffiti", wear: "Monarch Blue", price: 995.72, image: "https://s3.upgrader.pro/cdn/items/23405/medium.png", rarity: "uncommon" },
  { id: "skin-63", name: "Magmatude", weapon: "Charm", wear: "FN", price: 219.19, image: "https://s3.upgrader.pro/cdn/items/15207/medium.png", rarity: "rare" },
  { id: "skin-64", name: "Gold Toof", weapon: "Glock-18", wear: "Well-Worn", price: 3539.86, image: "https://s3.upgrader.pro/cdn/items/14117/medium.png", rarity: "legendary" },
  { id: "skin-65", name: "Moonrise", weapon: "Glock-18", wear: "Battle-Scarred", price: 190.71, image: "https://s3.upgrader.pro/cdn/items/8948/medium.png", rarity: "rare" },
  { id: "skin-66", name: "Kiss♥Love", weapon: "Sawed-Off", wear: "Well-Worn", price: 362.44, image: "https://s3.upgrader.pro/cdn/items/2219/medium.png", rarity: "mythical" },
  { id: "skin-67", name: "Tropical Storm", weapon: "Souvenir SSG 08", wear: "Battle-Scarred", price: 1580.32, image: "https://s3.upgrader.pro/cdn/items/16329/medium.png", rarity: "common" },
  { id: "skin-68", name: "Faulty Wiring", weapon: "FAMAS", wear: "Minimal Wear", price: 183.63, image: "https://s3.upgrader.pro/cdn/items/12328/medium.png", rarity: "uncommon" },
  { id: "skin-69", name: "Liquidation", weapon: "M4A1-S", wear: "Factory New", price: 1206.56, image: "https://s3.upgrader.pro/cdn/items/3005/medium.png", rarity: "rare" },
  { id: "skin-70", name: "Half Sleeve", weapon: "FAMAS", wear: "Factory New", price: 189.40, image: "https://s3.upgrader.pro/cdn/items/1039/medium.png", rarity: "common" },
  { id: "skin-71", name: "USTILO (Foil)", weapon: "Sticker", wear: "Boston 2018", price: 1299.81, image: "https://s3.upgrader.pro/cdn/items/20945/medium.png", rarity: "rare" },
  { id: "skin-72", name: "Ace Devil", weapon: "Sticker", wear: "Foil", price: 364.17, image: "https://s3.upgrader.pro/cdn/items/12135/medium.png", rarity: "mythical" },
  { id: "skin-73", name: "Autumn Twilly", weapon: "MP5-SD", wear: "Minimal Wear", price: 1415.18, image: "https://s3.upgrader.pro/cdn/items/12351/medium.png", rarity: "rare" },
  { id: "skin-74", name: "Skadoodle", weapon: "Sticker", wear: "Boston 2018", price: 419.17, image: "https://s3.upgrader.pro/cdn/items/17644/medium.png", rarity: "uncommon" },
  { id: "skin-75", name: "Chopper", weapon: "P90", wear: "Well-Worn", price: 206.05, image: "https://s3.upgrader.pro/cdn/items/7448/medium.png", rarity: "rare" },
  { id: "skin-76", name: "Wild Child", weapon: "UMP-45", wear: "Battle-Scarred", price: 310.53, image: "https://s3.upgrader.pro/cdn/items/13631/medium.png", rarity: "mythical" },
  { id: "skin-77", name: "Falcons (Foil) | Austin 2025", weapon: "Sticker Slab", wear: "FN", price: 155.39, image: "https://s3.upgrader.pro/cdn/items/26372/medium.png", rarity: "rare" },
  { id: "skin-78", name: "Weasel", weapon: "Glock-18", wear: "Minimal Wear", price: 180.17, image: "https://s3.upgrader.pro/cdn/items/1728/medium.png", rarity: "rare" },
  { id: "skin-79", name: "Slate", weapon: "AK-47", wear: "Field-Tested", price: 487.80, image: "https://s3.upgrader.pro/cdn/items/2279/medium.png", rarity: "rare" },
  { id: "skin-80", name: "Red Stone", weapon: "SSG 08", wear: "Minimal Wear", price: 1252.69, image: "https://s3.upgrader.pro/cdn/items/10886/medium.png", rarity: "uncommon" }
]

const DEFAULT_INVENTORY: InventoryItem[] = [
  { uid: "inv-1", skinId: "skin-18" },
  { uid: "inv-2", skinId: "skin-16" },
  { uid: "inv-3", skinId: "skin-4" },
  { uid: "inv-4", skinId: "skin-11" },
]

export const DEFAULT_STATE: AppState = {
  balance: 1500,
  inventory: DEFAULT_INVENTORY,
  skins: DEFAULT_SKINS,
  upgradeSkins: DEFAULT_SKINS,
  loggedIn: false,
  username: "Player",
  avatar: null,
  online: 2172,
  upgrades: 132860345,
  predict: { outcome: "off", targetSkinId: null, hint: "x2", targetLosses: 3, currentLosses: 0, showPercentages: true, showMultipliers: true },
  adminPassword: "admin123",
  fastMode: false,
  fastMultipliers: [2, 4, 8],
  fastPercentages: [35, 55, 75],
  soundMode: "on",
}

export const RARITY_COLORS: Record<string, string> = {
  common: "#5e98d9",
  uncommon: "#4b69ff",
  rare: "#8847ff",
  mythical: "#d32ce6",
  legendary: "#eb4b4b",
  ancient: "#e4ae39",
}
