import type { Skin, AppState, InventoryItem } from "./types"

export const DEFAULT_SKINS: Skin[] = [
  {
    id: "m4a4-howl",
    name: "Howl",
    weapon: "StatTrak™ M4A4",
    wear: "FN",
    price: 945450,
    image: "/assets/images/skins/skin-25.png",
    rarity: "ancient",
  },
  {
    id: "ak47-wild-lotus",
    name: "Wild Lotus",
    weapon: "AK-47",
    wear: "FN",
    price: 1232867,
    image: "/assets/images/skins/skin-28.png",
    rarity: "ancient",
  },
  {
    id: "butterfly-doppler",
    name: "Doppler Sapphire",
    weapon: "★ Butterfly Knife",
    wear: "FN",
    price: 828521,
    image: "/assets/images/skins/skin-2.png",
    rarity: "legendary",
  },
  {
    id: "awp-dragon-lore",
    name: "Dragon Lore",
    weapon: "AWP",
    wear: "FN",
    price: 760854,
    image: "/assets/images/skins/skin-29.png",
    rarity: "ancient",
  },
  {
    id: "karambit-fade",
    name: "Fade",
    weapon: "★ Karambit",
    wear: "FN",
    price: 681458,
    image: "/assets/images/skins/skin-4.png",
    rarity: "legendary",
  },
  {
    id: "sport-gloves-vice",
    name: "Vice",
    weapon: "★ Sport Gloves",
    wear: "MW",
    price: 640840,
    image: "/assets/images/skins/skin-11.png",
    rarity: "mythical",
  },
  {
    id: "deagle-blaze",
    name: "Blaze",
    weapon: "Desert Eagle",
    wear: "FN",
    price: 64550,
    image: "/assets/images/skins/skin-16.png",
    rarity: "rare",
  },
  {
    id: "glock-fade",
    name: "Fade",
    weapon: "Glock-18",
    wear: "FN",
    price: 32400,
    image: "/assets/images/skins/skin-4.png",
    rarity: "rare",
  },
  {
    id: "ak47-redline",
    name: "Redline",
    weapon: "StatTrak™ AK-47",
    wear: "MW",
    price: 4850,
    image: "/assets/images/skins/skin-18.png",
    rarity: "uncommon",
  },
  {
    id: "awp-asiimov",
    name: "Asiimov",
    weapon: "AWP",
    wear: "FT",
    price: 8900,
    image: "/assets/images/skins/skin-16.png",
    rarity: "rare",
  },
  {
    id: "glock-water",
    name: "Water Elemental",
    weapon: "Glock-18",
    wear: "MW",
    price: 1250,
    image: "/assets/images/skins/skin-6.png",
    rarity: "common",
  },
  {
    id: "deagle-blaze-mw",
    name: "Blaze",
    weapon: "Desert Eagle",
    wear: "MW",
    price: 540,
    image: "/assets/images/skins/skin-10.png",
    rarity: "common",
  },
  {
    id: "m4a1-neon-rider",
    name: "Neon Rider",
    weapon: "M4A1-S",
    wear: "FN",
    price: 18700,
    image: "/assets/images/skins/skin-20.png",
    rarity: "mythical",
  },
  {
    id: "ak47-vulcan",
    name: "Vulcan",
    weapon: "AK-47",
    wear: "FN",
    price: 12400,
    image: "/assets/images/skins/skin-18.png",
    rarity: "rare",
  },
  {
    id: "awp-flashback",
    name: "Flashback",
    weapon: "AWP",
    wear: "MW",
    price: 6300,
    image: "/assets/images/skins/skin-16.png",
    rarity: "rare",
  },
  {
    id: "five-seven-triumvirate",
    name: "Triumvirate",
    weapon: "Five-SeveN",
    wear: "FN",
    price: 2850,
    image: "/assets/images/skins/skin-15.png",
    rarity: "uncommon",
  },
  {
    id: "galil-cold-fusion",
    name: "Cold Fusion",
    weapon: "Souvenir Galil AR",
    wear: "FN",
    price: 3200,
    image: "/assets/images/skins/skin-14.png",
    rarity: "uncommon",
  },
  {
    id: "xm1014-hieroglyph",
    name: "Hieroglyph",
    weapon: "XM1014",
    wear: "FN",
    price: 1800,
    image: "/assets/images/skins/skin-13.png",
    rarity: "uncommon",
  },
  {
    id: "aug-navy-murano",
    name: "Navy Murano",
    weapon: "AUG",
    wear: "MW",
    price: 950,
    image: "/assets/images/skins/skin-12.png",
    rarity: "common",
  },
  {
    id: "famas-sergeant",
    name: "Sergeant",
    weapon: "StatTrak™ FAMAS",
    wear: "FN",
    price: 720,
    image: "/assets/images/skins/skin-1.png",
    rarity: "common",
  },
  {
    id: "sg553-aerial",
    name: "Aerial",
    weapon: "SG 553",
    wear: "FN",
    price: 430,
    image: "/assets/images/skins/skin-2.png",
    rarity: "common",
  },
  {
    id: "sg553-lush-ruins",
    name: "Lush Ruins",
    weapon: "SG 553",
    wear: "MW",
    price: 890,
    image: "/assets/images/skins/skin-3.png",
    rarity: "uncommon",
  },
  {
    id: "glock-vogue",
    name: "Vogue",
    weapon: "Glock-18",
    wear: "FN",
    price: 5400,
    image: "/assets/images/skins/skin-4.png",
    rarity: "mythical",
  },
  {
    id: "glock-axia",
    name: "Axia",
    weapon: "Glock-18",
    wear: "FN",
    price: 1100,
    image: "/assets/images/skins/skin-6.png",
    rarity: "uncommon",
  },
  {
    id: "m4a4-polysoup",
    name: "Polysoup",
    weapon: "M4A4",
    wear: "FN",
    price: 650,
    image: "/assets/images/skins/skin-7.png",
    rarity: "common",
  },
  {
    id: "cz75-midnight-palm",
    name: "Midnight Palm",
    weapon: "CZ75-Auto",
    wear: "FT",
    price: 380,
    image: "/assets/images/skins/skin-8.png",
    rarity: "common",
  },
  {
    id: "m4a1-wasteland",
    name: "Wasteland Rebel",
    weapon: "M4A1-S",
    wear: "MW",
    price: 2100,
    image: "/assets/images/skins/skin-9.png",
    rarity: "uncommon",
  },
  {
    id: "deagle-phoenix",
    name: "Phoenix Blacklight",
    weapon: "Desert Eagle",
    wear: "FN",
    price: 7800,
    image: "/assets/images/skins/skin-10.png",
    rarity: "mythical",
  },
  {
    id: "ak47-forest-ddpat",
    name: "Forest DDPAT",
    weapon: "AK-47",
    wear: "FT",
    price: 310,
    image: "/assets/images/skins/skin-17.png",
    rarity: "common",
  },
  {
    id: "ak47-sand-dune",
    name: "Sand Dune",
    weapon: "AK-47",
    wear: "FT",
    price: 280,
    image: "/assets/images/skins/skin-19.png",
    rarity: "common",
  },
]

const DEFAULT_INVENTORY: InventoryItem[] = [
  { uid: "inv-1", skinId: "ak47-redline" },
  { uid: "inv-2", skinId: "awp-asiimov" },
  { uid: "inv-3", skinId: "glock-fade" },
  { uid: "inv-4", skinId: "deagle-blaze" },
]

export const DEFAULT_STATE: AppState = {
  balance: 1500,
  inventory: DEFAULT_INVENTORY,
  skins: DEFAULT_SKINS,
  loggedIn: false,
  username: "Player",
  avatar: null,
  online: 2172,
  upgrades: 132860345,
  predict: { outcome: "off", targetSkinId: null, hint: "x2" },
  adminPassword: "admin123",
}

export const RARITY_COLORS: Record<string, string> = {
  common: "#5e98d9",
  uncommon: "#4b69ff",
  rare: "#8847ff",
  mythical: "#d32ce6",
  legendary: "#eb4b4b",
  ancient: "#e4ae39",
}
